spring:
  application:
    name: study-kafka-consumer-app
  datasource:
    url: jdbc:postgresql://jerry.world:32222/ad
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:30092
    streams:
      application-id: impression-agg
      client-id: impression-agg-client
      properties:
        commit.interval.ms: 1000
        cache.max.bytes.buffering: 10485760
        processing.guarantee: exactly_once_v2
  jpa:
    hibernate:
      ddl-auto: update