spring:
  application:
    name: study-kafka-consumer-app
  datasource:
    url: jdbc:postgresql://jerry.world:32222/ad
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:30092
    consumer:
      enable-auto-commit: false
      isolation-level: read_committed
  jpa:
    hibernate:
      ddl-auto: update